### PR TITLE
Pseudotv 4:3 channel bug position update

### PR DESCRIPTION
**Pull request by XeXoasz**
Here I created an update that  adds positions for 4:3 channel bug positions and labeled the old positions 16:9

### CODE REVIEW

**Comment by fnord12** [comment]
Hey XeXoasz, thanks for submitting this request.   Do i understand correctly that the idea is for the channel bug to always appear over the actual video?  So that for a 4:3 video, it will/can shift over to appear over the video instead of appearing in the black bar?   I think that's cool, but i actually prefer for it to remain in the same place no matter what, so if i take this commit i want to make sure users will have the option for either.   Is that possible in your current submission (i.e. users can set the position for 4:3 and 16:9 to be the same in the code) or should we add a little toggle button in the settings somewhere?

**Comment by XeXoasz** [comment]
Hi fnord, 

I added strings here that labels the new postions 4:3 and the old positions 16:9. If people decide to use 4:3 position it will remain on the video even on 16:9. It doesn't shift over based on the video however, just in the same place that's in the setting. Basically it is just 4 extra options in the channel bug placement choosing with the old options 16:9 and new ones 4:3. I divided the pox x coordinates couple times to figure out where the logo will end up. Hopefully people find this useful :)

**Comment by XeXoasz** [comment]
Should be good to go now, changed the position spacing to the ones I had on my file, the spacing was off earlier.

**Comment by fnord12** [comment]
Excellent.   I'll test it out this weekend and then i'll commit it to a new branch.  Thanks for your contribution, awesome to see people using and improving PseudoTV!

**Pull request merged**
